services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: fraud-zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: fraud-kafka
    depends_on: [zookeeper]
    ports:
      - "${KAFKA_PORT}:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://fraud-kafka:9092,EXTERNAL://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: 24

  postgres:
    image: postgres:16-alpine
    container_name: fraud-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - fraud_pg_data:/var/lib/postgresql/data

volumes:
  fraud_pg_data:
