apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-provisioning-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/khang/Code/data-pipeline/fraud-detection-pipeline/monitoring/grafana/provisioning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-provisioning-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  volumeName: grafana-provisioning-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/khang/Code/data-pipeline/fraud-detection-pipeline/monitoring/grafana/dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  volumeName: grafana-dashboards-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "fraudadmin"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/var/lib/grafana/dashboards/fraud_pipeline.json"
          volumeMounts:
            - name: provisioning-volume
              mountPath: /etc/grafana/provisioning
              readOnly: true
            - name: dashboards-volume
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
            - name: storage-volume
              mountPath: /var/lib/grafana
      volumes:
        - name: provisioning-volume
          persistentVolumeClaim:
            claimName: grafana-provisioning-pvc
        - name: dashboards-volume
          persistentVolumeClaim:
            claimName: grafana-dashboards-pvc
        - name: storage-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: grafana
